### ISSUE TITLE
file extension skipped for all files when requiresjs option is set

### ISSUE THREAD

**Issue by Joe04** [stryju/grunt-bushcaster#10]
When requirejs option is set to true all files are having the extension skipped so they are replaced like:
filename-{hash}.extension 

I would expect for non scripts to be: filename.extension-{hash}

**Comment by stryju** [comment]
sorry for the long time with no action - what's the use-case?

it doesn't really make sense to replace the extension, as this might break some behaviour...

**Comment by Joe04** [comment]
you are right, the behaviour is totally fine, it was a misunderstanding from my side
